name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.9.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.13
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v2

      - name: AWS Credentials
        run: |
          aws configure --profile default set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure --profile default set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure --profile default set region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Deploy
        run: |
          terraform init
          terraform import aws_dynamodb_table.terraform_state_lock
          terraform import aws_s3_bucket.terraform_states
          terraform plan -no-color 
          terraform apply -auto-approve
          echo ${{ steps.plan.outputs.stdout }}
          echo ${{ steps.plan.outputs.stderr }}
          echo ${{ steps.plan.outputs.exitcode }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}